apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-rating-movie-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: theater
  template:
    metadata:
      labels:
        app: theater
    spec:
      containers:
        - name: rating-service
          image: trucnguyen301197/rating-service:latest
          ports:
            - containerPort: 8086
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: TrucNguyen123
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://theater-db:3306/rating?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          imagePullPolicy: Always
        - name: movie-service
          image: trucnguyen301197/movie-service:latest
          ports:
            - containerPort: 8087
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: TrucNguyen123
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://theater-db:3306/movie?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          imagePullPolicy: Always
        - name: aws-service
          image: trucnguyen301197/aws-service:latest
          ports:
            - containerPort: 8085
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: aws-rating-movie-service
spec:
  selector:
    app: theater
  ports:
    - name: aws-service
      port: 8085
      targetPort: 8085
      protocol: TCP
      nodePort: 31300
    - name: rating-service
      port: 8086
      targetPort: 8086
      protocol: TCP
      nodePort: 31000
    - name: movie-service
      port: 8087
      targetPort: 8087
      protocol: TCP
      nodePort: 31100
  type: NodePort